sonar.projectKey=kalisio-kazarr
sonar.sources=src,main.py,conversion_tool/src,conversion_tool/main.py
sonar.tests=test
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11
sonar.exclusions=**/__pycache__/**,**/*.pyc
sonar.coverage.exclusions=**/test/**,**/logs/**,**/main.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverageReportPaths=coverage.xml
